### ISSUE TITLE
Lab Webpage: TODO List

### ISSUE THREAD

**Issue by batflyer** [boost-starai/boost-starai.github.io#8]
What still needs to be done on the Lab Webpage, what is currently in progress, and where is it being worked on?

* [x] Datasets
  * [x] [software_and_datasets branch](https://github.com/batflyer/boost-starai.github.io/tree/software_and_datasets)
* [ ] Authors
  * [ ] [site_authors branch](https://github.com/batflyer/boost-starai.github.io/tree/site_authors)
  * [ ] Hero image on people page is mis-aligned
* [ ] Publications
  * [x] .pdf, code, slides, video, posters.
  * [ ]  bibTeX 
  * [ ] sorting 
  * [x] Mobile compatibility
* [x] Lab News
  * [x] On home page / integrated with the blog.
  * [ ] How to maintain over time?
* [ ] Blog
  * [ ] Define tags for specific purposes: Lab News, Tutorials.
* [ ]  BoostSRL Wiki
  * [ ] How to maintain over time?
  * [ ] Wiki template for future pages.
  * [ ] Scripts for updating/inserting pages?
* [ ] Analytics
  * `UA-99296192-3`

**Comment by batflyer** [comment]
Setting this  issue to closed. This makes more sense to maintain through the Projects tab than as an issue. If discussion is necessary for a certain issue, it can be opened.
